### ISSUE TITLE
Version without session storage?

### ISSUE THREAD

**Issue by TAG4-21** [JoniRinta-Kahila/microsoft-login-spoof#1]
Im looking for just the pure site, with nothing else then the capacity to input login credentials then after that nothing happens. Could you please help me out?

**Comment by JoniRinta-Kahila** [comment]
Hi, sorry for the late reply.
If I understood correctly, you want to disable the password collection feature?
If you meant this, make the following changes:

in script.js
Comment out line 134, where sendData was called.
And all the lines where sessionStorage was called  1-3, 131,132,137,139.
Lines 140-144  which caused a redirect after submitting the form.

Update index.html to import script.js instead of script.min.js in line 54.

Please note that I have committed new changes to this project, so the line numbering I have given may differ from the older version.
